"""Decide permutation equivalence inside the cyclic two-block family.

A WL signature collision only FLAGS a possible duplicate; it is a necessary
condition, never a sufficient one. For the family that holds most of the top of
this board, the question can be decided outright, and this module does that, so
a flag becomes a yes or a no rather than a review item nobody closes.

A GB code on Z_m is H_X = [circ(a) | circ(b)]. The maps that carry one such
code onto another as a PERMUTATION of qubits and checks are generated by:
  x -> x^u for a unit u mod m   (a ring automorphism, so a relabelling)
  a -> x^s a, b -> x^t b        (cyclic shifts of each block)
  (a, b) -> (b, a)              (exchanging the two qubit blocks)
Two codes are equivalent under these iff some (u, s, t, swap) carries the
exponent set of one pair onto the other. That is a finite search: phi(m) units
times m shifts, and the shifts are pinned by matching one element, so it costs
O(phi(m) * m) set comparisons rather than a search over permutations.

This decides the family that holds most of the board's top entries, which is
what the WL signature cannot do on its own.
"""
import collections
import glob
import json
import re
import sys
from math import gcd


def support(doc, which):
    """Read the a(x) and b(x) exponent sets from the check matrix itself."""
    n = doc["n"]
    m = n // 2
    X = doc["checks"]["X"]
    row = None
    for r in X:
        if 0 in r:
            row = sorted(r)
            break
    if row is None:
        row = sorted(X[0])
    a = sorted(q for q in row if q < m)
    b = sorted(q - m for q in row if q >= m)
    return m, a, b


def normalise(e, m):
    """Return the lexicographically least cyclic translate."""
    e = sorted(x % m for x in e)
    best = None
    for s in e:
        cand = tuple(sorted((x - s) % m for x in e))
        if best is None or cand < best:
            best = cand
    return best


def equivalent(d1, d2):
    """Return (u, swap) when a unit map carries d1 onto d2, else None."""
    m1, a1, b1 = support(d1, "X")
    m2, a2, b2 = support(d2, "X")
    if m1 != m2 or sorted(map(len, (a1, b1))) != sorted(map(len, (a2, b2))):
        return None
    m = m1
    t2 = (normalise(a2, m), normalise(b2, m))
    for u in range(1, m):
        if gcd(u, m) != 1:
            continue
        ua = normalise([x * u for x in a1], m)
        ub = normalise([x * u for x in b1], m)
        if (ua, ub) == t2:
            return (u, False)
        if (ub, ua) == t2:
            return (u, True)
    return None


def scan(paths):
    """Decide every same-(n, k) pair among two-block entries.

    Returns the list of (a, b, (unit, swapped)) that are genuinely equivalent.
    """
    docs = {}
    for path in paths:
        try:
            with open(path, encoding="utf-8") as f:
                c = json.load(f)
        except (OSError, ValueError):
            continue
        if not c.get("checks", {}).get("X"):
            continue
        n = c["n"]
        if n % 2 or len(c["checks"]["X"]) != n // 2:
            continue                       # not the two-block shape
        docs[re.sub(r"\.json$", "", path.rsplit("/", 1)[-1])] = c
    by = collections.defaultdict(list)
    for s, c in docs.items():
        by[(c["n"], c["k"])].append(s)
    found = []
    for names in by.values():
        for i in range(len(names)):
            for j in range(i + 1, len(names)):
                try:
                    r = equivalent(docs[names[i]], docs[names[j]])
                except Exception:
                    r = None
                if r:
                    found.append((names[i], names[j], r))
    return sorted(found)


if __name__ == "__main__":
    if sys.argv[1:2] == ["--scan"]:
        hits = scan(sorted(glob.glob(sys.argv[2] if len(sys.argv) > 2
                                     else "codes/*.json")))
        for a, b, (u, sw) in hits:
            print(f"EQUIVALENT  {a}  ==  {b}   (x -> x^{u}"
                  f"{', blocks swapped' if sw else ''})")
        print(f"{len(hits)} permutation-equivalent pair(s)")
        raise SystemExit(1 if hits else 0)
    groups = json.loads(sys.argv[1])
    for g in groups:
        docs = {}
        for s in g:
            try:
                with open(f"codes/{s}.json", encoding="utf-8") as fh:
                    docs[s] = json.load(fh)
            except (OSError, ValueError):
                pass
        names = sorted(docs)
        if len(names) < 2:
            continue
        hits = []
        for i in range(len(names)):
            for j in range(i + 1, len(names)):
                r = equivalent(docs[names[i]], docs[names[j]])
                if r:
                    hits.append((names[i], names[j], r))
        if hits:
            for a, b, (u, sw) in hits:
                print(f"  EQUIVALENT  {a}  ==  {b}   (x -> x^{u}{', blocks swapped' if sw else ''})")
        else:
            print(f"  distinct    {', '.join(names)}")
